import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import SwapContextProvider from '@/context/swapContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SwapContextProvider>{children}</SwapContextProvider>
        <div id='portal'></div>
      </body>
    </html>
  )
}
